"""Shared constants for asset-engine pipeline behavior."""

AVG_WORDS_PER_SECOND = 2.5
MIN_CLIP_DURATION_SECONDS = 0.5
DEFAULT_SILENCE_SECONDS = 0.5

CONFIDENCE_EXACT = 1.0
CONFIDENCE_FALLBACK = 0.8
CONFIDENCE_MISSING = 0.0

MISSING_VOICE_POLICY = "silence_placeholder"
MISSING_MUSIC_POLICY = "skip"
MISSING_AMBIENCE_POLICY = "skip"
MISSING_SFX_POLICY = "skip"
